/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gleason_superhockey_screens_HockeyScreen */

#ifndef _Included_org_gleason_superhockey_screens_HockeyScreen
#define _Included_org_gleason_superhockey_screens_HockeyScreen
#ifdef __cplusplus
extern "C" {
#endif
#undef org_gleason_superhockey_screens_HockeyScreen_TIME_STEP
#define org_gleason_superhockey_screens_HockeyScreen_TIME_STEP 0.022222223f
#undef org_gleason_superhockey_screens_HockeyScreen_VELOCITY_ITTERATIONS
#define org_gleason_superhockey_screens_HockeyScreen_VELOCITY_ITTERATIONS 2L
#undef org_gleason_superhockey_screens_HockeyScreen_POSITION_ITTERATIONS
#define org_gleason_superhockey_screens_HockeyScreen_POSITION_ITTERATIONS 8L
#undef org_gleason_superhockey_screens_HockeyScreen_BORDER_VAL
#define org_gleason_superhockey_screens_HockeyScreen_BORDER_VAL 10.0f
/*
 * Class:     org_gleason_superhockey_screens_HockeyScreen
 * Method:    resetScreen
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gleason_superhockey_screens_HockeyScreen_resetScreen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
