/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gleason_superhockey_opengl_model_Sprite */

#ifndef _Included_org_gleason_superhockey_opengl_model_Sprite
#define _Included_org_gleason_superhockey_opengl_model_Sprite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gleason_superhockey_opengl_model_Sprite
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gleason_superhockey_opengl_model_Sprite_init
  (JNIEnv *, jclass);

/*
 * Class:     org_gleason_superhockey_opengl_model_Sprite
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_gleason_superhockey_opengl_model_Sprite_resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_gleason_superhockey_opengl_model_Sprite
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gleason_superhockey_opengl_model_Sprite_render
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
